### PR TITLE
Merge develop into master

### PR DESCRIPTION
**Pull request by yurrriq**
Notably, this will publish [the latest PDF](https://github.com/idris-hackers/software-foundations/raw/develop/docs/pdf/sf-idris-2018.pdf), which now builds via Nix.

(Currently it only works via `nix-shell --run make` and not `nix-build`, but it's nearly bedtime...)

### CODE REVIEW

**Review by clayrat — DISMISSED** [review]

**Comment by clayrat** [comment]
Is this finished now?

**Comment by yurrriq** [comment]
It's finished, in that it builds successfully (verified on Travis, though the results are currently unused) and includes the updated (and renamed) PDF.

**Review by clayrat — APPROVED** [review]

**Comment by clayrat** [comment]
Should I merge it then?

**Comment by yurrriq** [comment]
Not if I merge it first :wink:

**Pull request merged**
