### PR TITLE
WIP: Poly

### PR DESCRIPTION
**Pull request by clayrat**
As requested in https://github.com/idris-hackers/software-foundations/issues/4

There'll be more text editing/rewriting to do in this one (at least in the first half), as implicits work a bit differently. Also module imports for overloaded functions seem a bit shaky - sometimes you have to qualify them, sometimes it works on its own.

### CODE REVIEW

**Comment by yurrriq** [comment]
Thanks for doing and opening this. I'll gladly take a look and try to help with any less easily translatable parts.

**Comment by clayrat** [comment]
Ok looks like I can't do much more with Poly, tell me what you think. Here's the gist of remaining `todo`s:
* First half should definitely be rewritten/rearranged
* There are two weird issues with `test_filter2` and `test_plus3'` which I don't know how to solve
* Minor weirdness with modules, also some of the exercises towards the end don't make sense to me

**Comment by yurrriq** [comment]
Sounds good. Thanks. I think I should be able to get to this later today.

**Comment by yurrriq** [comment]
Merging this for now. We can make changes later.

**Pull request merged**
