### PR TITLE
Imp

### PR DESCRIPTION
**Pull request by clayrat**

### CODE REVIEW

**Comment by clayrat** [comment]
They spend a large chunk of this chapter introducing more tactics like `try` and `omega`. Some of those exist in Pruviloj, and the new tactics don't really get used in the remainder of the chapter, so we should probably move this part to the hypothetical `Pruviloj` chapter.

**Comment by yurrriq** [comment]
Sounds good to me.

**Comment by clayrat** [comment]
Should be ready for review.

I'm not too happy about introducing multiple names for `AExp`/`CEval`/etc but couldn't figure out how to compartmentalize them with `namespace`s.

**Comment by yurrriq** [comment]
Let's hold off on this until we finish up to Rel and push a new PDF.

**Comment by yurrriq** [comment]
If you want to merge this one too, go ahead, @clayrat.

**Comment by clayrat** [comment]
Let's do this one too

**Pull request merged**
