### PR TITLE
IndPrinciples

### PR DESCRIPTION
**Pull request by clayrat**
Gah, yet another seemingly useless chapter. Not even sure I want to waste more time formatting this, given that it probably needs to be completely rewritten or dropped altogether. Thoughts?

### CODE REVIEW

**Comment by clayrat** [comment]
So, AFAIU induction principles are subsumed/made obsolete by dependent pattern matching. We could try salvaging some examples/theory to add to the potential `Tactics` -> `PatternMatching` rewrite, but this should probably be done by someone who actually knows how these things work internally in Idris. Plus, again, the second part talks about `IndProp`-ish things, so it would result in sequence breaking.

**Comment by yurrriq** [comment]
Is this complete, if not useless?

**Comment by clayrat** [comment]
No, I've only formatted ~1/3 and got frustrated. Maybe I'll have another look soon.

**Comment by clayrat** [comment]
Ok, I figured I could just write out the induction principles by hand to illustrate the concept. Still not sure if Idris actually works like that internally though.

**Comment by clayrat** [comment]
This SO question looks relevant: https://stackoverflow.com/questions/30598260/function-definition-by-induction-principles-in-agda

**Comment by clayrat** [comment]
Should be ok to review.

**Comment by clayrat** [comment]
So, any chance for this to get merged? :)

**Comment by clayrat** [comment]
Resolves https://github.com/idris-hackers/software-foundations/issues/42

**Comment by yurrriq** [comment]
I'm a little swamped atm and it's only gonna got worse until at least Monday. If you feel good about it, go ahead and merge. :smile:

**Comment by clayrat** [comment]
Ok I think this has been hanging far too long :)

**Comment by yurrriq** [comment]
:tada:

**Pull request merged**
